<?php echo $this->paginator; ?>
<h2>Товары</h2>
<p><a href="<?php echo $this->url(array('action' => 'add', 'controller' => 'catalog'), 'admin') ?>" role="button" class="btn btn-success add">
        Добавить товар
</a></p>
<table class="table">
    <thead>
        <tr>
            <th>Опубликован</th>
            <th>Заголовок</th>
            <th>Категория</th>
            <th>Бренд</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->items as $item): ?>
        <tr>
            <td style="width: 100px;"><?php if ($item['is_published']): ?><i class="icon-ok"></i><?php endif; ?></td>
            <td><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'catalog', 'action' => 'edit'), 'admin') ?>"><?php echo $item['title'] ?></a></td>
            <td><?php echo $item['category_title']; ?></td>
            <td><?php echo $item['brand_title']; ?></td>
            <td style="width: 40px;"><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'catalog', 'action' => 'delete'), 'admin') ?>" class="icon-trash pull-right action delete"></a></td>
            <td style="width: 40px;"><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'catalog', 'action' => 'edit'), 'admin') ?>" class="icon-edit pull-right action edit"></a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->paginator; ?>
