<div id="left_catalog"></div>
<div id="right_catalog">
    <?php echo $this->partial('nav.phtml', 'default', array('page' => $this->page)); ?>
    <h3 class="news_title"><span><?php echo $this->page->getTitle(); ?></span></h3>
    <?php foreach ($this->news as $news): ?>
        <div style="padding-bottom: 20px;">
            <div class="news-date-time" style="font-size: .8em;">
                <span class="news-date"><?php echo date('d\.m\.Y', strtotime($news['published_at'])); ?></span>
                <span class="news-time"><?php echo date('H:i', strtotime($news['published_at'])); ?></span>
            </div>
            <h3><a href="/news/<?php echo $news['page_url']; ?>"><?php echo $news['title']; ?></a></h3>
            <div class="news-text">
                <?php echo $news['content']; ?>
            </div>

        </div>
    <?php endforeach; ?>
</div>