<div id="left_catalog"></div>
<div id="right_catalog">
    <?php echo $this->partial('nav.phtml', 'default', array('page' => $this->page)); ?>
    <h3 class="news_title"><span><?php echo $this->page->getTitle(); ?></span></h3>
    <?php if (!empty($this->flashMessages)): ?>
        <?php echo $this->page->getContent(); ?>
    <?php else: ?>
        <div class="message_param" id="comment">
            <?php echo $this->form; ?>
        </div>
    <?php endif; ?>
</div>