<?php echo $this->paginator; ?>
<h2>Тексты на страницах</h2>
<!--<p><a href="--><?php //echo $this->url(array('action' => 'add', 'controller' => 'page-text'), 'admin') ?><!--" role="button" class="btn btn-success add">Добавить текст</a></p>-->

    <?php
        $groupedItems = array();
        foreach ($this->items as $item) {
            if (!array_key_exists($item['group'], $groupedItems)) {
                $groupedItems[$item['group']] = array(
                    'title' => $item['group_title'],
                    'name' => $item['group'],
                    'items' => array(),
                );
            }
            $groupedItems[$item['group']]['items'][] = $item;
        }
    ?>

    <div class="accordion" id="page-text-accordion">

        <?php foreach ($groupedItems as $group): ?>
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#page-text-accordion" href="#group-<?php echo $group['name'] ?>">
                        <h4><?php echo $group['title'] ?></h4>
                    </a>
                </div>
                <div id="group-<?php echo $group['name'] ?>" class="accordion-body collapse">
                    <div class="accordion-inner">
                        <table class="table">
                            <tbody>
                            <?php foreach ($group['items'] as $item): ?>
                                <tr>
                                    <td><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'page-text', 'action' => 'edit'), 'admin') ?>"><?php echo $item['position']; ?></a></td>
                                    <td><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'page-text', 'action' => 'edit'), 'admin') ?>"><?php echo $item['title']; ?></a></td>
<!--                                    <td style="width: 40px;"><a href="--><?php //echo $this->url(array('id' => $item['id'], 'controller' => 'page-text', 'action' => 'delete'), 'admin') ?><!--" class="icon-trash pull-right action delete"></a></td>-->
                                    <td style="width: 40px;"><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'page-text', 'action' => 'edit'), 'admin') ?>" class="icon-edit pull-right action edit"></a></td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        <?php endforeach; ?>
    </div>
<?php echo $this->paginator; ?>

