<h1>Часто задаваемые вопросы</h1>

<ul class="faqs-list">
    <?php foreach ($this->items as $item): ?>
        <li class="faqs-question"><h3><?php echo $item['question']; ?></h3>
            <div class="faqs-answer">
                <?php echo $item['answer']; ?>
            </div>
        </li>
    <?php endforeach; ?>
</ul>

<script>
    $('.faqs-list .faqs-answer').hide();
    $('.faqs-question h3').click(function() {
        $(this).parent().find('.faqs-answer').slideToggle('fast', function() {
            $(this).parent().toggleClass('selected');
        });
    });
</script>

<div class="bg-grad-gray">
    <h3 class="question-form-header">Задать вопрос</h3>
    <div class="question-form">
        <?php echo $this->form; ?>
    </div><!-- .register-form -->
</div><!-- .bg-grad-gray -->