<?php echo $this->paginator; ?>
<h2>Заявки</h2>
<table class="table">
    <thead>
        <tr>
            <th>Текст</th>
            <th>E-mail</th>
            <th>Телефон</th>
            <th>Имя</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->items as $item): ?>
        <tr>
            <td><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'feedback', 'action' => 'edit'), 'admin') ?>"><?php echo substr($this->escape($item['content']), 0, 40); ?>...</a></td>
            <td><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'feedback', 'action' => 'edit'), 'admin') ?>"><?php echo $this->escape($item['email']); ?></a></td>
            <td><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'feedback', 'action' => 'edit'), 'admin') ?>"><?php echo $this->escape($item['phone']); ?></a></td>
            <td><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'feedback', 'action' => 'edit'), 'admin') ?>"><?php echo $this->escape($item['name']); ?></a></td>
            <td style="width: 40px;"><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'feedback', 'action' => 'delete'), 'admin') ?>" class="icon-trash pull-right action delete"></a></td>
            <td style="width: 40px;"><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'feedback', 'action' => 'edit'), 'admin') ?>" class="icon-edit pull-right action edit"></a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->paginator; ?>
