<?php echo $this->paginator; ?>
<h2>Заявки</h2>
<table class="table">
    <thead>
        <tr>
            <th>Опубликован</th>
            <th>Текст</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->items as $item): ?>
        <tr>
            <td style="width: 100px;"><?php if ($item['is_published']): ?><i class="icon-ok"></i><?php endif; ?></td>
            <td><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'feedback', 'action' => 'edit'), 'admin') ?>"><?php echo $this->escape($item['question']); ?></a></td>
            <td style="width: 40px;"><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'feedback', 'action' => 'delete'), 'admin') ?>" class="icon-trash pull-right action delete"></a></td>
            <td style="width: 40px;"><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'feedback', 'action' => 'edit'), 'admin') ?>" class="icon-edit pull-right action edit"></a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->paginator; ?>
