<div id="navigation">
    <?php echo $this->partial('nav.phtml', 'default', array('page' => $this->page)); ?>
</div>
<script src="http://api-maps.yandex.ru/2.0-stable/?load=package.full&lang=ru-RU" type="text/javascript"></script>
<div id="map"></div> <!--map-->
<div id="contact_info">
    <p id="contact_title"><?php echo $this->page->getTitle() ?></p>
    <div id="contacts_page">
        <div class="contact_page">
            <p class="adress_phone">АДРЕС ОФИСА:</p>
            <p><?php echo $this->settings['address'] ?></p>
        </div>
        <div class="contact_page">
            <p class="adress_phone">ТЕЛЕФОН:</p>
            <p><?php echo $this->settings['phone'] ?></p>
        </div>
    </div>
</div>
<div id="news">
    <h3 id="contact_news_title"><span>НОВОСТИ</span></h3>
    <div id="contact_point"></div>
    <div class="news_contact">
        <p>Акция на полированный керамогранит в ноябре 06.11.2012 <br> <a href="#">подробнее</a></p>
        <p>Расширение линейки полированного керамогранита 31.10.2012<br> <a href="#">подробнее</a></p>
        <p> Специальная цена до 1 ноября - белый полированный керамогранит! 15.10.2012 <br> <a href="#">подробнее</a></p>
    </div>
</div>
<script>
    ymaps.ready(init);
    var myMap;

    function init(){
        myMap = new ymaps.Map ("map", {
            center: [55.675306, 37.624741],
            behaviors: ['scrollZoom', 'drag', 'multiTouch'],
            zoom: 15
        });
        var myPlacemark = new ymaps.Placemark([<?php echo $this->settings['coordinates'] ?>], { // [55.675306, 37.624741]
            // Чтобы балун и хинт открывались на метке, необходимо задать ей определенные свойства.
            balloonContentHeader: "Рекада",
            balloonContentBody: "<?php echo $this->settings['address'] ?>",
            balloonContentFooter: "<?php echo $this->settings['phone'] ?>",
            hintContent: "Рекада"
        });

        myMap.geoObjects.add(myPlacemark);

        myPlacemark.balloon.open();
    }
</script>
<div id="location">
    <?php echo $this->page->getContent(); ?>
</div>
<div id="messager">
    <form method="post" action="/feedback">
        <div class="message_param">
            <p>Имя</p>
            <input name="name" type="text" size="20" required />
        </div>
        <div class="message_param">
            <p>Email<sup>*</sup></p>
            <input name="email" type="text" size="20" required />
        </div>
        <div class="message_param">
            <p>Телефон:</p>
            <input name="phone" type="text" size="20"/>
        </div>
        <div id="comment">
            <p>Ваш вопрос/сообщение</p>
            <textarea name="content" rows="7"> </textarea>
        </div>
        <input type="submit" id="contact_button" value=""/>
    </form>
</div>