<div id="left_catalog"></div>
<div id="right_catalog">
    <div style="padding: 50px;">
        <h3 class="news_title"><span>При выполнениии запроса произошла ошибка</span></h3>
        <h3 class="news_title"><span><?php echo $this->message ?></span></h3>
    </div>

    <?php if (isset($this->exception)): ?>
        <!--
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>
  -->

    <?php endif ?>
</div>
