<?php echo $this->paginator; ?>
<h2>Страницы</h2>
<p><a href="<?php echo $this->url(array('action' => 'add', 'controller' => 'page'), 'admin') ?>" role="button" class="btn btn-success add">
        Добавить страницу
</a></p>

<?php foreach ($this->items as $item): ?>
<ul class="unstyled">
    <li>
        <span class="span6">
            <a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => 'page', 'action' => 'edit'), 'admin') ?>">
                <?php echo $item['title'] ?>
            </a>
        </span>
        <span class="span1">
            <?php if ($item['is_published']): ?><i class="icon-ok"></i><?php endif; ?>
        </span>
        <a title="Добавить подстраницу" href="<?php echo $this->url(array('action' => 'add', 'controller' => 'page'), 'admin') ?>" class="icon-plus"></a>
    </li>
</ul>
<?php endforeach; ?>
<?php echo $this->paginator; ?>