<a href="<?php echo $this->url(array('action' => 'index', 'id' => null, 'controller' => 'rek'), 'admin'); ?>"><i class="icon-arrow-left"></i> вернуться к списку</a> или
<a href="<?php echo $this->url(array('action' => 'index', 'id' => null, 'controller' => 'category'), 'admin'); ?>"><i class="icon-arrow-left"></i> вернуться к дереву</a>
<h2>Добавление рекомандаций</h2>
<?php print $this->paramsForm; ?>
<?php print $this->form; ?>