<div id="footer">
    <!-- <div id="line">
    </div>-->
    <div id="info">
        <div class="contact">
            <span class="h5">КОНТАКТЫ</span>
            <p><?php echo $this->settings['address'] ?></p>
            <p><a href="/contacts">схема проезда&nbsp;&gt;&gt;</a></p>
            <p><span><?php echo $this->settings['phone'] ?></span></p>
        </div>
       <!--  <div class="line_y">
        </div>-->
        <div class="info_sclad">
            <span class="h5">АДРЕСА СКЛАДОВ</span>
            <p>Восток: Реутов, ул. Транспортная 11Б</p>
            <p>Север: Москва, Чермянский пр. 4А</p>
            <p>Центр: Москва, Спартаковская пл. 1/7</p>
        </div>
        <!--   <div class="line_y">
        </div>-->
        <div class="info_sclad">
            <span class="h5">ДОСТАВКА И ОПЛАТА</span>
            <p>Доставка автотранспортом</p>
            <p>Наличная оплата</p>
            <p>Безналичная оплата</p>
        </div>
         <!--  <div class="line_y">
        </div>-->
        <div class="contact">
            <span class="h5">КАТАЛОГ</span>

            <?php foreach ($this->categoryNavigation as $category): ?>
                <p>
                    <a href ="/catalog/<?php echo $category['page_url']; ?>"><?php echo $category['title']; ?></a>
                </p>
            <?php endforeach; ?>
        </div>
    </div>
    <div id="footer_footer">
        <div id="foot">
            <div id="foot_left"><a href="#">О КОМПАНИИ</a><a href="#">КАТАЛОГ</a><a href="#">БАЗА ЗНАНИЙ</a><a href="#">ПОРТФОЛИО</a><a href="#">КОНТАКТЫ</a></div>
            <div id="foot_right">&copy;&nbsp;2010-2012&nbsp;РЕКАДА</div>
        </div>
    </div>
</div>