<div id="footer">
    <div id="line">
    </div>
    <div id="info">
        <div class="contact">
            <h5>КОНТАКТЫ</h5>
            <p>Москва,</p>
            <p>Варшавское шоссе д.42</p>
            <p><a href="#">схема проезда&nbsp;&gt;&gt;</a></p>
            <p><span>8&nbsp;(495)&nbsp;921-40-44</span></p>
        </div>
        <div class="line_y">
        </div>
        <div class="info_sclad">
            <h5>АДРЕСА СКЛАДОВ</h5>
            <p>Восток: Реутов, ул. Транспортная 11Б</p>
            <p>Север: Москва, Чермянский пр. 4А</p>
            <p>Центр: Москва, Спартаковская пл. 1/7</p>
        </div>
        <div class="line_y">
        </div>
        <div class="info_sclad">
            <h5>ДОСТАВКА И ОПЛАТА</h5>
            <p>Доставка автотранспортом</p>
            <p>Наличная оплата</p>
            <p>Безналичная оплата</p>
        </div>
        <div class="line_y">
        </div>
        <div class="contact">
            <h5>КАТАЛОГ</h5>
            <p>Керамогранит</p>
            <p>Вентфасады</p>
            <p>Натуральный камень</p>
            <p>Гидроабразивная резка</p>
        </div>
    </div>
    <div id="footer_footer">
        <div id="foot">
            <div id="foot_left"><a href="#">ГЛАВНАЯ</a><a href="#">О КОМПАНИИ</a><a href="#">КАТАЛОГ</a><a href="#">БАЗА ЗНАНИЙ</a><a href="#">ПОРТФОЛИО</a><a href="#">КОНТАКТЫ</a></div>
            <div id="foot_right">&copy;&nbsp;2010-2012&nbsp;РЕКАДА</div>
        </div>
    </div>
</div>