<div id="header">
    <div id="head">
        
<div id="logo">
            <a href="/"><img src="/img/logo.png"></a>
        </div>
         <div id="centr"><span>ЦЕНТР КЕРАМОГРАНИТА И ВЕНТФАСАДОВ</span><img src="/img/phone.png"><span><a><?php echo substr($this->settings['phone'], 3, 5) ?></a><strong><?php echo substr($this->settings['phone'], 9) ?></strong></span></div>

    </div>
<p id="menu">
        <a href="/about" class="space">О КОМПАНИИ</a>
        <a class="space" href="/articles">РЕКОМЕНДАЦИИ</a>
        <a class="space" href="/gallery">ГАЛЕРЕЯ</a>
        <a class="space" href="/contacts">КОНТАКТЫ</a>
        <a class="menu_left" href="/feedback">ОСТАВИТЬ ЗАЯВКУ</a>
     <!--     <a class="menu_left" href="/files/<?php echo $this->settings['price'] ?>">ПРАЙС&nbsp;</a>-->
    </p>
<!--    <form action="/search" method="post"><input id="search" type="text" name="searchstring" value="&#160;поиск" onfocus="this.value=''" onblur="this.value='поиск'"/></form>-->
<!--  <a href="" id="search_field">-->
<!--        <input type="image" src="/img/search_button.png" value="" id="search_button"/>-->
<!--    </a>-->
    <div id="product" class="product_menu">
        <?php $i = 1 ?>
        <ul>
            <?php $rPage = $this->page->getRaw(); ?>
        <?php foreach ($this->categoryNavigation as $category): ?>

            <?php $cur = false; if ($rPage['page_url'] === $category['page_url'] || (!empty($rPage['parents'][1]) && '/' . $category['page_url'] == $rPage['parents'][1]['url'])) {$cur = true; } ?>
            <li class="dop_menu <?php echo $cur ? 'active' : ''; ?>">
                <a class="prod" href ="/<?php echo $category['page_url']; ?>"><?php echo $category['title']; ?></a>
                <?php
                    $brandModel = new Catalog_Model_BrandService();
                    $brands = $brandModel->fetchAll(array(array('key' => 'b.id_parent = ?', 'value' => $category['id'])), array('order'));
                ?>
                <ul>
                    <?php foreach ($brands as $brand): ?>
                        <li><a href="/<?php echo $category['page_url'] . '/' . $brand['page_url'] ?>"><?php echo $brand['title'] ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </li>
            <?php $i++ ?>
        <?php endforeach; ?>
        </ul>
    </div>
</div>