<div id="header">
    <div id="head">
        <div id="logo">
            <a href="/"><img src="/img/logo.png"></a>
        </div>
        <div id="centr"><span>ЦЕНТР КЕРАМОГРАНИТА И ВЕНТФАСАДОВ</span><img src="/img/phone.png"><span><a><?php echo substr($this->settings['phone'], 3, 5) ?></a><strong><?php echo substr($this->settings['phone'], 9) ?></strong></span></div>
    </div>
    <p id="menu">
        <a href="/about" class="space">О КОМПАНИИ</a>
        <a class="space" href="/articles">БАЗА ЗНАНИЙ</a>
        <a class="space" href="/gallery">ГАЛЕРЕЯ</a>
        <a class="space" href="/contacts">КОНТАКТЫ</a>
        <a class="menu_left" href="/feedback">ЗАЯВКА</a>
        <a class="menu_left" href="/files/<?php echo $this->settings['price'] ?>">ПРАЙС&nbsp;</a>
    </p>
    <a href="" id="search_field">
        <input type="image" src="/img/search_button.png" value="" id="search_button"/>
    </a>
    <form action="/search" method="post"><input id="search" type="text" name="searchstring" value="&#160;поиск" onfocus="this.value=''" onblur="this.value='поиск'"/></form>
    <div id="product" class="product_menu">
        <?php $i = 1 ?>
        <?php foreach ($this->categoryNavigation as $category): ?>
            <div id="toggle_1" class="dop_menu">
                <a class="prod" style="text-transform: uppercase;" href ="/<?php echo $category['page_url']; ?>"><?php echo $category['title']; ?></a>
            </div>
            <?php $i++ ?>
        <?php endforeach; ?>
    </div>
</div>