<head>
    <?php
    /** @var Whale_Page_Interface $page */
    $page = $this->page;
    ?>
    <title><?php echo $page->getTitle() ?></title>
    <meta name="description" content="<?php echo $page->getDescription() ?>">
    <meta name="keywords" content="<?php echo $page->getKeywords(); ?>">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/catalog.css">
    <link href="/css/jquery-ui-1.10.2.custom.css" rel="stylesheet">
    <script type="text/javascript" src="/js/jquery-1.9.1.min.js"></script>
    <script src="/js/jquery-ui-1.10.2.custom.js"></script>
    <script type="text/javascript" src="/js/rekada.js"></script>
    <script type="text/javascript" src="/js/checkbox.js"></script>
</head>