<head>
    <?php
    /** @var Whale_Page_Interface $page */
    $page = $this->page;
    ?>
    <title><?php echo $page->getTitle() ?></title>
    <meta name="description" content="<?php echo $page->getDescription() ?>">
    <meta name="keywords" content="<?php echo $page->getKeywords(); ?>">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,400,600,700|Open+Sans+Condensed:300,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/vendor/bootstrap/css/my.css" media="screen">
    <link rel="stylesheet" type="text/css" href="/css/style.css" media="screen">
    <link rel="stylesheet" type="text/css" href="/css/catalog.css" media="screen">
    <link rel="stylesheet" type="text/css" href="/css/shadowbox.css">

    <link rel="stylesheet" type="text/css" href="/css/print.css" media="print">
    <link href="/css/jquery-ui-1.10.2.custom.css" rel="stylesheet">
    <script type="text/javascript" src="/js/jquery-1.9.1.min.js"></script>
    <script src="/js/jquery-ui-1.10.2.custom.js"></script>
    <script type="text/javascript" src="/js/rekada.js?t=<?php echo time(); ?>"></script>
    <script type="text/javascript" src="/js/checkbox.js?t=<?php echo time(); ?>"></script>
    <script type="text/javascript" src="/js/shadowbox.js"></script>
    <script type="text/javascript">
        Shadowbox.init({
            language: 'ru',
            players: ['img'],
            overlayColor: '#fff'
        });
    </script>
</head>