
<div id="podmenu">
    <div class="hide_block" id="granit">
        <ul class ="hover_block">
            <li><a href="#">РОССИЯ</a><span>|</span></li>
            <li><a href="#">КИТАЙ</a><span>|</span></li>
            <li><a href="#">ИТАЛИЯ</a><span>|</span></li>
            <li><a href="#">ОАЭ</a></li>
        </ul>
    </div>
    <div class="hide_block" id="fasad">
        <ul class ="hover_block">
            <li><a href="#">КЕРАМОГРАНИТ</a><span>|</span></li>
            <li><a href="#">ФИБРОЦЕМЕНТ</a><span>|</span></li>
            <li><a href="#">ДЛЯ КОТТЕДЖЕЙ</a><span>|</span></li>
            <li><a href="#">МЕТАЛЛОКАССЕТЫ</a></li>
        </ul>
    </div>
    <div class="hide_block" id="kamen">
        <ul class ="hover_block" >
            <li><a href="#">МРАМОР</a><span>|</span></li>
            <li><a href="#">ГРАНИТ</a><span>|</span></li>
            <li><a href="#">АГЛОМЕРАТ</a></li>
        </ul>
    </div>
    <div class="hide_block" id="rezka">
        <ul class ="hover_block">
            <li><a href="#">СТУПЕНИ</a><span>|</span></li>
            <li><a href="#">ПОДОКОННИКИ</a><span>|</span></li>
            <li><a href="#">СТОЛЕШНИЦЫ</a><span>|</span></li>
            <li><a href="#">ПАННО, ДЕКОРЫ, БОРДЮРЫ</a><span>|</span></li>
            <li><a href="#">ОТВЕРСТИЯ</a></li>
        </ul>
    </div>
</div><!--podmenu-->