<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dmitry Groza">
    <link href="/vendor/bootstrap/css/metro.bootstrap.min.css" rel="stylesheet">
    <link href="/vendor/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/vendor/datepicker/css/datepicker.css" rel="stylesheet">
    <link href="/vendor/fancyBox/source/jquery.fancybox.css" rel="stylesheet">
    <link href="/vendor/jquery-ui-1.10.2.custom/css/plain-theme/jquery-ui-1.10.2.custom.css" rel="stylesheet">
    <style>
        /* sticky footer */
        html, body {
            height: 100%;
        }

        #wrap {
            min-height: 100%;
            height: auto !important;
            height: 100%;
            margin: 0 auto -60px;
        }

        footer {
            height: 60px;
        }
        #push {
            height: 80px;
        }
        @media (max-width: 767px) {
            #footer {
                margin-left: -20px;
                margin-right: -20px;
                padding-left: 20px;
                padding-right: 20px;
            }
        }
        /* /sticky footer */

        footer {
            background-color: #f5f5f5;
            line-height: 60px;
        }
        .admin-image {
            padding-right: 15px;
        }
    </style>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="/favicon.ico" />
    <script src="/vendor/jquery/jquery-1.9.1.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="/vendor/datepicker/js/bootstrap-datepicker.js"></script>
    <script src="/vendor/jQuery-File-Upload/js/vendor/jquery.ui.widget.js"></script>
    <script src="/vendor/jQuery-File-Upload/js/jquery.iframe-transport.js"></script>
    <script src="/vendor/jQuery-File-Upload/js/jquery.fileupload.js"></script>
    <script src="/vendor/fancyBox/source/jquery.fancybox.js"></script>
    <script src="/vendor/bootstrap-wysiwyg/bootstrap-wysiwyg.js"></script>
    <script src="/vendor/ckeditor/ckeditor.js"></script>
    <script src="/vendor/jquery-ui-1.10.2.custom/js/jquery-ui-1.10.2.custom.js"></script>

    <script src="/js/script.js"></script>
</head>

<body>
<div id="wrap">
    <div class="navbar navbar-top navbar-inverse">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="/admin">Admin</a>

                <div class="nav-collapse">
                    <ul class="nav">
                        <li><a href="/admin/news">Новости</a></li>
                        <li><a href="/admin/faq">FAQ</a></li>
                        <li><a href="/admin/gallery">Галерея</a></li>
                        <li><a href="/admin/page-text">Тексты</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="/catalog">
                                Каталог
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                                <li><a href="/admin/product">Товары</a></li>
                                <li><a href="/admin/category">Категории</a></li>
                                <li><a href="/admin/brand">Бренды</a></li>
                                <li><a href="/admin/thesaurus">Справочники</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav pull-right">
                        <li><a href="/">Сайт</a></li>
                        <li class="divider-vertical"></li>
                        <li><a href="/logout">Выйти</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid main">
        <div class="row-fluid">
            <div class="span10">
                <div class="row-fluid">
                    <?php if (!empty($this->flashMessages)): ?>
                    <div id="app-messages">
                        <?php foreach ($this->flashMessages as $message): ?>
                        <div class="alert"><?php echo $message; ?><a class="close" data-dismiss="alert">×</a></div>
                        <?php endforeach; ?>
                    </div>
                    <?php endif; ?>
                    <div id="app-container">
                        <?php echo $this->layout()->content; ?>
                    </div>
                    <div id="app-modal"></div>
                </div>
            </div>
            <div class="span2" id="app-sidebar">
<!--                --><?php //echo $this->navigation()->menu(); ?>
            </div>
        </div>
    </div>
    <div id="push"></div>
</div>
<footer>
    <div class="container-fluid">
        &copy; 2013 <i>to Insomnia with Love</i>
    </div>
</footer>
</body>
</html>