<!DOCTYPE html>
<html>
    <head>
        <title>Отделка</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" type="text/css" href="/css/style.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="/css/jquery.lightbox-0.5.css" media="screen" />
        <script type="text/javascript" src="/js/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="/js/jquery.lightbox-0.5.js"></script>
        <script type="text/javascript" src="/js/rekada.js"></script>
    </head>
    <body>
        <div id="wrapper">
            <?php echo $this->render('_header.phtml') ?>
            <div id="content">
                <div id="navigation">
                    <p><a href="index.html">ГЛАВНАЯ</a><span>/</span> ИСПОЛЬЗОВАНИЕ КЕРАМОГРАНИТА В ПРОЕКТАХ</p>
                </div>
                <div id="gallery">
                    <p class="gallery_name">Внутренняя отделка</p>
                    <?php echo $this->layout()->content; ?>
                </div>
            </div> <!--content-->
            <?php echo $this->render('_footer.phtml') ?>
        </div>
    </body>
</html>
