<!DOCTYPE html>
<html>
    <head>
        <title>Отделка</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" type="text/css" href="/css/style.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="/css/jquery.lightbox-0.5.css" media="screen" />
        <script type="text/javascript" src="/js/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="/js/jquery.lightbox-0.5.js"></script>
        <script type="text/javascript" src="/js/rekada.js"></script>
    </head>
    <body>
        <div id="wrapper">
            <?php echo $this->render('_header.phtml') ?>
            <div id="content">
                <div id="navigation">
                    <p><a href="index.html">ГЛАВНАЯ</a><span>/</span> ИСПОЛЬЗОВАНИЕ КЕРАМОГРАНИТА В ПРОЕКТАХ</p>
                </div>
                <div id="gallery">
                    <p class="gallery_name">Внутренняя отделка</p>
                    <div class="plita_left"><img src="/img/gallery/photo1.jpg">
                        <div class="inblock">
                            <div class="pict_gallery"><a href="/img/images/photo1.jpg" title="РИСУНОК 1" >
                                <img src="/img/search.png" height="20px" width="20px"/>посмотреть</a>
                            </div>
                            <p class="cost_gallery"><a href="#">CGA6625K</a></p>
                            <p class="model_gallery"><a href="#">Estima</a></p>
                            <p class="cost_gallery">540 <span>руб./м<a>2</a></span></p>
                            <p class="zakaz_gallery"><a href="">ЗАКАЗАТЬ</a></p>
                        </div>
                    </div>
                    <div class="plita_left"><img src="/img/gallery/photo2.jpg">
                        <div class="inblock">
                            <div class="pict_gallery"><a href="/img/images/photo2.jpg" title="РИСУНОК 2" >
                                <img src="/img/search.png" height="20px" width="20px"/>посмотреть</a>
                            </div>
                            <p class="cost_gallery"><a href="#">CGA6625K</a></p>
                            <p class="model_gallery"><a href="#">Estima</a></p>
                            <p class="cost_gallery">540 <span>руб./м<a>2</a></span></p>
                            <p class="zakaz_gallery"><a href="">ЗАКАЗАТЬ</a></p>
                        </div>
                    </div>
                    <div class="plita_left"><img src="/img/gallery/photo3.jpg">
                        <div class="inblock">
                            <div class="pict_gallery"><a href="/img/images/photo3.jpg" title="РИСУНОК 3" >
                                <img src="/img/search.png" height="20px" width="20px"/>посмотреть</a>
                            </div>
                            <p class="cost_gallery"><a href="#">CGA6625K</a></p>
                            <p class="model_gallery"><a href="#">Estima</a></p>
                            <p class="cost_gallery">540 <span>руб./м<a>2</a></span></p>
                            <p class="zakaz_gallery"><a href="">ЗАКАЗАТЬ</a></p>
                        </div>
                    </div>
                    <div class="plita_right"><img src="/img/gallery/photo4.jpg">
                        <div class="inblock">
                            <div class="pict_gallery"><a href="/img/images/photo4.jpg" title="РИСУНОК 4" >
                                <img src="/img/search.png" height="20px" width="20px"/>посмотреть</a>
                            </div>
                            <p class="cost_gallery"><a href="#">CGA6625K</a></p>
                            <p class="model_gallery"><a href="#">Estima</a></p>
                            <p class="cost_gallery">540 <span>руб./м<a>2</a></span></p>
                            <p class="zakaz_gallery"><a href="">ЗАКАЗАТЬ</a></p>
                        </div>
                    </div>
                    <div class="plita_left"><img src="/img/gallery/photo5.jpg">
                        <div class="inblock">
                            <div class="pict_gallery"><a href="/img/images/photo5.jpg" title="РИСУНОК 5" >
                                <img src="/img/search.png" height="20px" width="20px"/>посмотреть</a>
                            </div>
                            <p class="cost_gallery"><a href="#">CGA6625K</a></p>
                            <p class="model_gallery"><a href="#">Estima</a></p>
                            <p class="cost_gallery">540 <span>руб./м<a>2</a></span></p>
                            <p class="zakaz_gallery"><a href="">ЗАКАЗАТЬ</a></p>
                        </div>
                    </div>
                    <div class="plita_left"><img src="/img/gallery/photo6.jpg">
                        <div class="inblock">
                            <div class="pict_gallery"><a href="/img/images/photo6.jpg"  title="РИСУНОК 6" >
                                <img src="/img/search.png" height="20px" width="20px"/>посмотреть</a>
                            </div>
                            <p class="cost_gallery"><a href="#">CGA6625K</a></p>
                            <p class="model_gallery"><a href="#">Estima</a></p>
                            <p class="cost_gallery">540 <span>руб./м<a>2</a></span></p>
                            <p class="zakaz_gallery"><a href="">ЗАКАЗАТЬ</a></p>
                        </div>
                    </div>
                    <div class="plita_left"><img src="/img/gallery/photo7.jpg">
                        <div class="inblock">
                            <div class="pict_gallery"><a href="/img/images/photo7.jpg" title="РИСУНОК 7" >
                                <img src="/img/search.png" height="20px" width="20px"/>посмотреть</a>
                            </div>
                            <p class="cost_gallery"><a href="#">CGA6625K</a></p>
                            <p class="model_gallery"><a href="#">Estima</a></p>
                            <p class="cost_gallery">540 <span>руб./м<a>2</a></span></p>
                            <p class="zakaz_gallery"><a href="">ЗАКАЗАТЬ</a></p>
                        </div>
                    </div>
                    <div class="plita_right"><img src="/img/gallery/photo8.jpg">
                        <div class="inblock">
                            <div class="pict_gallery"><a href="/img/images/photo8.jpg" title="РИСУНОК 8" >
                                <img src="/img/search.png" height="20px" width="20px"/>посмотреть</a>
                            </div>
                            <p class="cost_gallery"><a href="#">CGA6625K</a></p>
                            <p class="model_gallery"><a href="#">Estima</a></p>
                            <p class="cost_gallery">540 <span>руб./м<a>2</a></span></p>
                            <p class="zakaz_gallery"><a href="">ЗАКАЗАТЬ</a></p>
                        </div>
                    </div>
                    <div class="plita_left"><img src="/img/gallery/photo9.jpg">
                        <div class="inblock">
                            <div class="pict_gallery"><a href="/img/images/photo9.jpg" title="РИСУНОК 9" >
                                <img src="/img/search.png" height="20px" width="20px"/>посмотреть</a>
                            </div>
                            <p class="cost_gallery"><a href="#">CGA6625K</a></p>
                            <p class="model_gallery"><a href="#">Estima</a></p>
                            <p class="cost_gallery">540 <span>руб./м<a>2</a></span></p>
                            <p class="zakaz_gallery"><a href="">ЗАКАЗАТЬ</a></p>
                        </div>
                    </div>
                    <div class="plita_left"><img src="/img/gallery/photo10.jpg">
                        <div class="inblock">
                            <div class="pict_gallery"><a href="/img/images/photo10.jpg" title="РИСУНОК 10" >
                                <img src="/img/search.png" height="20px" width="20px"/>посмотреть</a>
                            </div>
                            <p class="cost_gallery"><a href="#">CGA6625K</a></p>
                            <p class="model_gallery"><a href="#">Estima</a></p>
                            <p class="cost_gallery">540 <span>руб./м<a>2</a></span></p>
                            <p class="zakaz_gallery"><a href="">ЗАКАЗАТЬ</a></p>
                        </div>
                    </div>
                    <div class="plita_left"><img src="/img/gallery/photo11.jpg">
                        <div class="inblock">
                            <div class="pict_gallery"><a href="/img/images/photo11.jpg" title="РИСУНОК 11" >
                                <img src="/img/search.png" height="20px" width="20px"/>посмотреть</a>
                            </div>
                            <p class="cost_gallery"><a href="#">CGA6625K</a></p>
                            <p class="model_gallery"><a href="#">Estima</a></p>
                            <p class="cost_gallery">540 <span>руб./м<a>2</a></span></p>
                            <p class="zakaz_gallery"><a href="">ЗАКАЗАТЬ</a></p>
                        </div>
                    </div>
                    <p class="gallery_link"><a class="open_link" href="gallery.html"><img src="/img/back.png">Отделка</a><span>|</span><a class="next_link" href="#">Фасады<img src="/img/next.png"></a></p>
                </div>
            </div> <!--content-->  
            <div id="footer">
                <div id="line">
                </div>
                <div id="info">
                    <div class="contact">
                        <h5>КОНТАКТЫ</h5>
                        <p>Москва,</p>
                        <p>Варшавское шоссе д.42</p>
                        <p><a href="#">схема проезда&nbsp;&gt;&gt;</a></p>
                        <p><span>8&nbsp;(495)&nbsp;921-40-44</span></p>
                    </div>
                    <div class="line_y">
                    </div>
                    <div class="info_sclad">
                        <h5>АДРЕСА СКЛАДОВ</h5>
                        <p>Восток: Реутов, ул. Транспортная 11Б</p>
                        <p>Север: Москва, Чермянский пр. 4А</p>
                        <p>Центр: Москва, Спартаковская пл. 1/7</p>
                    </div>
                    <div class="line_y">
                    </div>
                    <div class="info_sclad">
                        <h5>ДОСТАВКА И ОПЛАТА</h5>
                        <p>Доставка автотранспортом</p>
                        <p>Наличная оплата</p>
                        <p>Безналичная оплата</p>
                    </div>
                    <div class="line_y">
                    </div>
                     <div class="contact">
                        <h5>КАТАЛОГ</h5>
                        <p>Керамогранит</p>
                        <p>Вентфасады</p>
                        <p>Натуральный камень</p>
                        <p>Гидроабразивная резка</p>
                    </div>
                </div>
                <div id="footer_footer">
                    <div id="foot">
                        <div id="foot_left"><a href="#">ГЛАВНАЯ</a><a href="#">О КОМПАНИИ</a><a href="#">КАТАЛОГ</a><a href="#">БАЗА ЗНАНИЙ</a><a href="#">ПОРТФОЛИО</a><a href="#">КОНТАКТЫ</a></div>
                        <div id="foot_right">&copy;&nbsp;2010-2012&nbsp;РЕКАДА</div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
