<!DOCTYPE html>
<html>
<head>
    <?php
    /** @var Whale_Page_Interface $page */
    $page = $this->page;
    ?>
    <title><?php echo $page->getTitle() ?></title>
    <meta name="description" content="<?php echo $page->getDescription() ?>">
    <meta name="keywords" content="<?php echo $page->getKeywords(); ?>">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/shadowbox.css">
    <script type="text/javascript" src="/js/shadowbox.js"></script>
    <script type="text/javascript">
        Shadowbox.init({
            language: 'ru',
            players: ['img']
        });
    </script>
    <script type="text/javascript" src="/js/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="/js/rekada.js"></script>
</head>
<body>
<div id="wrapper">

<?php echo $this->render('_header.phtml') ?>
<div id="content">
    <div id="keramo">
        <div id="podmenu">
            <div class="hide_block" id="granit">
                <ul class ="hover_block">
                    <li><a href="#">РОССИЯ</a><span>|</span></li>
                    <li><a href="#">КИТАЙ</a><span>|</span></li>
                    <li><a href="#">ИТАЛИЯ</a><span>|</span></li>
                    <li><a href="#">ОАЭ</a></li>
                </ul>
            </div>
            <div class="hide_block" id="fasad">
                <ul class ="hover_block">
                    <li><a href="#">КЕРАМОГРАНИТ</a><span>|</span></li>
                    <li><a href="#">ФИБРОЦЕМЕНТ</a><span>|</span></li>
                    <li><a href="#">ДЛЯ КОТТЕДЖЕЙ</a><span>|</span></li>
                    <li><a href="#">МЕТАЛЛОКАССЕТЫ</a></li>
                </ul>
            </div>
            <div class="hide_block" id="kamen">
                <ul class ="hover_block" >
                    <li><a href="#">МРАМОР</a><span>|</span></li>
                    <li><a href="#">ГРАНИТ</a><span>|</span></li>
                    <li><a href="#">АГЛОМЕРАТ</a></li>
                </ul>
            </div>
            <div class="hide_block" id="rezka">
                <ul class ="hover_block">
                    <li><a href="#">СТУПЕНИ</a><span>|</span></li>
                    <li><a href="#">ПОДОКОННИКИ</a><span>|</span></li>
                    <li><a href="#">СТОЛЕШНИЦЫ</a><span>|</span></li>
                    <li><a href="#">ПАННО, ДЕКОРЫ, БОРДЮРЫ</a><span>|</span></li>
                    <li><a href="#">ОТВЕРСТИЯ</a></li>
                </ul>
            </div>
        </div>
        <div id="keramo_text">
            <h1><a href="catalog_keramo.html">КЕРАМОГРАНИТ</a></h1>
            <p>Оптовые поставки материала из наличия-</p>
            <p>Подбор вариантов для Вашего объекта-</p>
            <p>Индивидуальные скидки для подрядчиков-</p>
            <p id="keramo_nal"><a  href="#">Узнать наличие&#160;&#62;&#62;</a></p>
        </div>
    </div>
    <div id="keramika">
        <div id="gradient"></div>
        <div id="choice">
            <h2><a href="#">АКЦИИ</a></h2>
            <h2><a href="#">ХИТЫ</a></h2>
            <h2><a href="#">НОВИНКИ</a></h2>
        </div>
        <div id="plitka">
            <?php foreach ($this->items as $item): ?>
                <div class="block"> <img style="height: 190px" src="/files/<?php echo $item['image'] ?>">
                    <div class="inblock">
                        <div class="pict"><a rel="shadowbox[Vacation]" href="/files/<?php echo $item['image'] ?>" ><img src="img/search.png" />посмотреть</a></div>
                        <p class="cost"><a href="#"><?php echo $item['article'] ?></a></p>
                        <p class="model"><a href="#"><?php echo $item['brand_title'] ?></a></p>
                        <p class="cost"><?php echo $item['cost'] ?> <span>руб./м<a>2</a></span></p>
                        <p class="zakaz"><a href="/catalog/<?php echo $item['category_page_url'] . '/' . ($item['page_url'] ?: $product['id']) ?>">ЗАКАЗАТЬ</a></p>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div>
        <div id="news">
            <h3 class="news_title"><span>НОВОСТИ</span></h3>
            <div id="point"></div>
            <div class="news">
                <?php foreach ($this->news as $news): ?>
                    <p>
                        <b><?php echo $news['title'] . '</b><br />' . $news['preview'] . ' ' . date('d.m.Y', strtotime($news['published_at'])); ?><br>
                        <a href="<?php echo $this->url(array('module' => 'news', 'controller' => 'index', 'action' => 'view', 'id' => $news['id'])); ?>">подробнее</a>
                    </p>
                <?php endforeach; ?>
            </div>
        </div>
        <div id="answer">
            <h3 class="news_title"><span>ПОЧЕМУ ВЫБИРАЮТ НАС?</span></h3>
            <div id="point_answer"></div>
            <div class="article">
                <h4><?php echo $this->texts->get('first')->getTitle(); ?></h4>
                <?php echo $this->texts->get('first')->getContent(); ?>
            </div>
            <div class="article">
                <h4><?php echo $this->texts->get('second')->getTitle(); ?></h4>
                <?php echo $this->texts->get('second')->getContent(); ?>
            </div>
            <div class="article">
                <h4><?php echo $this->texts->get('third')->getTitle(); ?></h4>
                <?php echo $this->texts->get('third')->getContent(); ?>
            </div>
        </div>
    </div>
    <div id="partner">
        <img src="/img/gasprom.png">
        <img src="/img/Rusgidro.png">
        <img src="/img/mosenergo.png">
        <img src="/img/sinterra.png">
        <img src="/img/gasprom.png">
    </div>
</div>

    <?php echo $this->render('_footer.phtml') ?>
</div>
</body>
</html>