<!DOCTYPE html>
<html>
<head>
    <?php
    /** @var Whale_Page_Interface $page */
    $page = $this->page;
    ?>
    <title><?php echo $page->getTitle() ?></title>
    <meta name="description" content="<?php echo $page->getDescription() ?>">
    <meta name="keywords" content="<?php echo $page->getKeywords(); ?>">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,400,600,700|Open+Sans+Condensed:300,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/shadowbox.css">
    <link rel="stylesheet" type="text/css" href="/vendor/bootstrap/css/my.css">
    <script type="text/javascript" src="/js/shadowbox.js"></script>
    <script type="text/javascript">
        Shadowbox.init({
            language: 'ru',
            players: ['img']
        });
    </script>
    <script type="text/javascript" src="/js/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="/vendor/bootstrap/js/my.min.js"></script>
    <script type="text/javascript" src="/js/rekada.js"></script>
</head>
<body>
<div id="wrapper">

<?php echo $this->render('_header.phtml') ?>
<div id="content">
<div id="gradient"></div>
    <div id="keramo" class="tw-bs">
        <div id="myCarousel" class="carousel slide">
            <ol class="carousel-indicators">
                <?php foreach ($this->slider as $key => $slider): ?>
                    <li data-target="#myCarousel" data-slide-to="<?php echo $key; ?>"></li>
                <?php endforeach; ?>
            </ol>
            <div class="carousel-inner">
                <?php foreach ($this->slider as $key => $slider): ?>
                <div class="item <?php if ($key == 0) echo 'active'; ?>">
                    <a href="<?php echo $slider['url']; ?>">
                        <img src="/files/<?php echo $slider['image']; ?>" alt="">
                        <div class="carousel-caption" id="keramo_text">
                            <b><?php echo $slider['title']; ?></b>
                            <?php echo $slider['text']; ?>
                        </div>
                    </a>
                </div>
                <?php endforeach; ?>
            </div>
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
        </div>
    </div>
    <div id="keramika">
        <div id="gradient"></div>
        <ul id="choice">
            <li class="active"><a href="#" class="data-plitka" data-plitka=".plitka-action">АКЦИИ</a></li>
            <li><a href="#" class="data-plitka" data-plitka=".plitka-hit">ХИТЫ</a></li>
            <li><a href="#" class="data-plitka" data-plitka=".plitka-new">НОВИНКИ</a></li>
        </ul>
        <script>
            $(document).ready(function(){
                    $('.carousel').carousel({
                        interval: 3000
                    });

                    $('.carousel').carousel('cycle');


                $('.data-plitka').on('click', function(){
                    $('.plitka').hide().filter($(this).attr('data-plitka')).fadeIn();
                    $('#choice li').removeClass('active');
                    $(this).parent('li').addClass('active');
                    return false;
                });
            });
        </script>
        <div class="plitka plitka-action">
            <?php foreach ($this->itemsAction as $item): ?>
                <div class="block"> <img style="height: 190px" src="/files/thumbnail/<?php echo $item['image'] ?>">
                    <div class="inblock">
                        <div class="pict"><a rel="shadowbox[Vacation]" href="/files/<?php echo $item['image'] ?>" ><img src="img/search.png" />посмотреть</a></div>
                        <p class="cost"><a href="#"><?php echo $item['article'] ?></a></p>
                        <p class="model"><a href="#"><?php echo $item['brand_title'] ?></a></p>
                        <p class="cost"><?php echo $item['cost'] ?> <span>руб./м<a>2</a></span></p>
                        <p class="zakaz"><a href="/<?php echo $item['category_page_url'] . '/' . $item['brand_page_url'] . '/' . $item['page_url'] ?>">ЗАКАЗАТЬ</a></p>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="plitka plitka-hit" style="display: none">
            <?php foreach ($this->itemsHit as $item): ?>
                <div class="block"> <img style="height: 190px" src="/files/thumbnail/<?php echo $item['image'] ?>">
                    <div class="inblock">
                        <div class="pict"><a rel="shadowbox[Vacation]" href="/files/<?php echo $item['image'] ?>" ><img src="img/search.png" />посмотреть</a></div>
                        <p class="cost"><a href="#"><?php echo $item['article'] ?></a></p>
                        <p class="model"><a href="#"><?php echo $item['brand_title'] ?></a></p>
                        <p class="cost"><?php echo $item['cost'] ?> <span>руб./м<a>2</a></span></p>
                        <p class="zakaz"><a href="<?php echo $item['category_page_url'] . '/' . $item['brand_page_url'] . '/' . $item['page_url'] ?>">ЗАКАЗАТЬ</a></p>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="plitka plitka-new" style="display: none">
            <?php foreach ($this->itemsNew as $item): ?>
                <div class="block"> <img style="height: 190px" src="/files/thumbnail/<?php echo $item['image'] ?>">
                    <div class="inblock">
                        <div class="pict"><a rel="shadowbox[Vacation]" href="/files/<?php echo $item['image'] ?>" ><img src="img/search.png" />посмотреть</a></div>
                        <p class="cost"><a href="#"><?php echo $item['article'] ?></a></p>
                        <p class="model"><a href="#"><?php echo $item['brand_title'] ?></a></p>
                        <p class="cost"><?php echo $item['cost'] ?> <span>руб./м<a>2</a></span></p>
                        <p class="zakaz"><a href="<?php echo $item['category_page_url'] . '/' . $item['brand_page_url'] . '/' . $item['page_url'] ?>">ЗАКАЗАТЬ</a></p>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="groupfix">
        <div id="news">
            <span class="news_title"><a href="/news/">НОВОСТИ</a></span>
            <div id="point"></div>
            <div class="news">
                <?php foreach ($this->news as $news): ?>
                    <p>
                        <b><?php echo $news['title'] . '</b><br />' . $news['preview'] . '<br />' . date('d.m.Y', strtotime($news['published_at'])); ?><br>
                        <a href="<?php echo $this->url(array('module' => 'news', 'controller' => 'index', 'action' => 'view', 'id' => $news['id'])); ?>">подробнее</a>
                    </p>
                <?php endforeach; ?>
            </div>
        </div>
        <div id="answer">
            <span class="news_title">ПОЧЕМУ ВЫБИРАЮТ НАС?</span>
            <div id="point_answer"></div>
            <div class="article">
               <!-- <span class="h4"><?php echo $this->texts->get('first')->getTitle(); ?></span>-->
                <?php echo $this->texts->get('first')->getContent(); ?>
            </div>
            <div class="article">
                <!--<span class="h4"><?php echo $this->texts->get('second')->getTitle(); ?></span>-->
                <?php echo $this->texts->get('second')->getContent(); ?>
            </div>
            <div class="article">
               <!-- <span class="h4"><?php echo $this->texts->get('third')->getTitle(); ?></span>-->
                <?php echo $this->texts->get('third')->getContent(); ?>
            </div>
        </div>
    </div>
     <div id="partner">
        <img src="/img/3morya.jpg">
        <img src="/img/mospromstroj.jpeg">
        <img src="/img/freper.jpg">
        <img src="/img/kosm.jpg">
            </div>
</div>

    <?php echo $this->render('_footer.phtml') ?>
</div>
</body>
</html>