<!DOCTYPE html>
<html>
    <head>
        <?php
        /** @var Whale_Page_Interface $page */
        $page = $this->page;
        ?>
        <title><?php echo $page->getTitle() ?></title>
        <meta name="description" content="<?php echo $page->getDescription() ?>">
        <meta name="keywords" content="<?php echo $page->getKeywords(); ?>">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" type="text/css" href="/css/style.css">
        <link rel="stylesheet" type="text/css" href="/css/catalog.css">
        <script type="text/javascript" src="/js/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="/js/rekada.js"></script>
    </head>
    <body>
        <div id="wrapper">
            <?php echo $this->render('_header.phtml') ?>

            <div id="content">
                <?php echo $this->render('_submenu.phtml') ?>
                <div id="left_catalog">
                    <p class="back_to_resault">&lt;&lt; <a href="#">назад&nbsp;&nbsp;к&nbsp;&nbsp;результатам</a></p>
                    <hr noshade size="1">
                    <p class="left_catalog_point">КОЛЛЕКЦИИ</p>
                    <div id="collection">
                        <p>Ажур</p>
                        <p>Арена</p>
                        <p>Атлант</p>
                        <p>Арно</p>
                        <p>Браво</p>
                        <p>Гавань</p>
                        <p>Глория</p>
                        <p>Гренобль</p>
                        <p>Дайсен</p>
                        <p>Дефанс</p>
                    </div>
                    <div id="collection">
                        <p>Дублин</p>
                        <p>Каре</p>
                        <p>Каскад</p>
                        <p>Кедр/Сонет</p>
                        <p>Кембридж</p>
                        <p>Креп/Гарда</p>
                        <p>Лагуна</p>
                        <p>Нарита</p>
                        <p>Магия</p>
                        <p>Марсель</p>
                    </div>
                    <div id="dekor">
                        <hr noshade size="1">
                        <p class="left_catalog_point">ДЕКОР</p>
                        <img src="/img/dekor_1.jpg">
                        <p class="dekor_model">B1726/SG9057</p>
                        <p class="dekor_size">30*7,2*8</p>
                        <img src="/img/dekor_2.jpg">
                        <p class="dekor_model">B1726/SG9057</p>
                        <p class="dekor_size">30*7,2*8</p>
                        <img src="/img/dekor_3.jpg">
                        <p class="dekor_model">B1726/SG9057</p>
                        <p class="dekor_size">30*7,2*8</p>
                        <img src="/img/dekor_4.jpg">
                        <p class="dekor_model">C1964/SG8014</p>
                        <p class="dekor_size">96*96*11</p>
                    </div>
                </div><!--left_catalog-->
                <?php echo $this->layout()->content; ?>
                    
                
            </div><!--content-->
            <div id="footer">
                <div id="line">
                </div>
                <div id="info">
                    <div class="contact">
                        <h5>КОНТАКТЫ</h5>
                        <p>Москва,</p>
                        <p>Варшавское шоссе д.42</p>
                        <p><a href="#">схема проезда&nbsp;&gt;&gt;</a></p>
                        <p><span>8&nbsp;(495)&nbsp;921-40-44</span></p>
                    </div>
                    <div class="line_y">
                    </div>
                    <div class="info_sclad">
                        <h5>АДРЕСА СКЛАДОВ</h5>
                        <p>Восток: Реутов, ул. Транспортная 11Б</p>
                        <p>Север: Москва, Чермянский пр. 4А</p>
                        <p>Центр: Москва, Спартаковская пл. 1/7</p>
                    </div>
                    <div class="line_y">
                    </div>
                    <div class="info_sclad">
                        <h5>ДОСТАВКА И ОПЛАТА</h5>
                        <p>Доставка автотранспортом</p>
                        <p>Наличная оплата</p>
                        <p>Безналичная оплата</p>
                    </div>
                    <div class="line_y">
                    </div>
                     <div class="contact">
                        <h5>КАТАЛОГ</h5>
                        <p>Керамогранит</p>
                        <p>Вентфасады</p>
                        <p>Натуральный камень</p>
                        <p>Гидроабразивная резка</p>
                    </div>
                </div>
                <div id="footer_footer">
                    <div id="foot">
                        <div id="foot_left"><a href="#">ГЛАВНАЯ</a><a href="#">О КОМПАНИИ</a><a href="#">КАТАЛОГ</a><a href="#">БАЗА ЗНАНИЙ</a><a href="#">ПОРТФОЛИО</a><a href="#">КОНТАКТЫ</a></div>
                        <div id="foot_right">&copy;&nbsp;2010-2012&nbsp;РЕКАДА</div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
