<div id="left_catalog"></div>
<div id="right_catalog">
    <div class="nav_catalog">
        <p>
        <?php foreach ($this->page->getParents() as $parent): ?>
            <a href="<?php echo $parent['url'] ?: '/'; ?>"><?php echo $parent['title']; ?></a> <span>/</span>
        <?php endforeach; ?>
            <?php echo $this->title ?>
        </p>
    </div>
    <h1><?php echo $this->title; ?></h1>
    <?php echo $this->content; ?>
</div>