<div class="block_available">
    <div class="catalog_available">
        <a href="/<?php echo $this->item['category_page_url'] . '/' . $this->item['brand_page_url'] . '/' . $this->item['page_url'] ?>"><img src="<?php echo getImage($this->item['image_preview']) ?>"></a>
    </div>
    <p><a href="/<?php echo $this->item['category_page_url'] . '/' . $this->item['brand_page_url'] . '/' . $this->item['page_url'] ?>"><?php echo $this->item['title'] ?></a></p>
</div>