<?php echo $this->render('search.phtml'); ?>
<div id="right_catalog">
    <div class="nav_catalog">
        <p><a href="/">Главная</a> <span>/</span> <?php echo $this->category['title'] ?> <span></p>
    </div>
    <div id="product-container" class="groupfix">
        <?php foreach ($this->products as $product): ?>
            <?php echo $this->partial('item.phtml', array('product' => $product)); ?>
        <?php endforeach; ?>
    </div>
    <?php echo $this->page->getContent(); ?>
    <div style="clear:both; height: 1px;" ></div>
    <div id="list_page">
<!--        <div class="prev_page">-->
<!--            <a href="#"><img src="/img/back.png"></a>-->
<!--        </div>-->
<!--        <p><span>1</span> <a href="#">2</a> <a href="#">3</a> .... <a href="#">8</a></p>-->
<!--        <div class="next_page">-->
<!--            <a href="#"><img src="/img/next.png"></a>-->
<!--        </div>-->
    </div>

</div>