<div id="left_catalog">
    <p class="back_to_resault">&lt;&lt; <a href="#" onclick="history.back(); return false;">назад&nbsp;&nbsp;к&nbsp;&nbsp;результатам</a></p>
    <hr noshade size="1">
    <?php if (!empty($this->collections)): ?>
        <p class="left_catalog_point">КОЛЛЕКЦИИ</p>
        <?php foreach ($this->collections as $collection): ?>
            <div class="area">
                <p><a href="<?php echo $collection['url'] ?>" class="area-link"><?php echo $collection['title'] ?></a></p>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
    <!--    <div id="dekor">-->
    <!--        <hr noshade size="1">-->
    <!--        <p class="left_catalog_point">ДЕКОР</p>-->
    <!--        <img src="/img/dekor_1.jpg">-->
    <!--        <p class="dekor_model">B1726/SG9057</p>-->
    <!--        <p class="dekor_size">30*7,2*8</p>-->
    <!--        <img src="/img/dekor_2.jpg">-->
    <!--        <p class="dekor_model">B1726/SG9057</p>-->
    <!--        <p class="dekor_size">30*7,2*8</p>-->
    <!--        <img src="/img/dekor_3.jpg">-->
    <!--        <p class="dekor_model">B1726/SG9057</p>-->
    <!--        <p class="dekor_size">30*7,2*8</p>-->
    <!--        <img src="/img/dekor_4.jpg">-->
    <!--        <p class="dekor_model">C1964/SG8014</p>-->
    <!--        <p class="dekor_size">96*96*11</p>-->
    <!--    </div>-->
</div><!--left_catalog-->
<?php echo $this->partial('itemList.phtml', array('products' => $this->products, 'page' => $this->page, 'title' => $this->rek['title'])); ?>