
<div id="right_catalog">
    <div class="nav_catalog">
        <p><a href="/">Главная</a>
            <span>/</span>
            <a href="/catalog/<?php echo $this->product['category_page_url'] ?>"><?php echo $this->product['category_title'] ?></a>
            <span>/</span>
            <a href="/catalog/<?php echo $this->product['category_page_url'] ?>/<?php echo $this->product['brand_page_url'] ?>">
                <?php echo $this->product['brand_title'] ?>
            </a>
            <span>/</span>
            <?php echo $this->product['title'] ?></p>
    </div>
    <div>
        <p class="name_black" style="text-transform: uppercase"><?php echo $this->product['title'] ?></p>
        <p class="name_blue" style="text-transform: uppercase"><?php echo $this->product['brand_title'] ?></p>
        <div class="catalog_sample">
            <img style="width:280px;" src="/files/<?php echo $this->product['image'] ?>"/>
        </div>
        <div class="sample_price">
            <p class="price_catalog"> <?php echo $this->product['cost'] ?> <span>руб./м</span></p>
            <p><span>Тип поверхности:</span> <?php echo $this->product['surface_title'] ?></p>
            <p><span>Размер:</span> <?php echo $this->product['width'] ?>*<?php echo $this->product['height'] ?>*<?php echo $this->product['depth'] ?></p>
<!--            <p><span>Рисунок:</span> дерево</p>-->
<!--            <p><span>Цвет:</span> серый</p>-->
            <input type="button" id="catalog_button" value="">
        </div>
    </div>
    <div id="catalog_info">
        <?php echo $this->product['content'] ?>
<!--        <p><span>Керамогранит Мираж</span> - это новинка, которая интересна тем, что искусно имитирует нерукотворные-->
<!--            трещины и канавки в камне, подвергшийся обработке.<br> Этот керамогранит под мрамор еще раз-->
<!--            доказывает, что природа может бесконечно давать нам повод восторгаться ее красотой.</p>-->
    </div>
    <div id="available">
        <p class="left_catalog_point">ДОСТУПНЫЕ ЦВЕТА:</p>
        <?php foreach ($this->productColors as $color): ?>
            <div class="block_available">
                <div class="catalog_available">
                    <img src="/files/<?php echo $color['image'] ?>">
                </div>
                <p><?php echo $this->product['title'] ?></p>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<div id="viewed">
    <div id="viewed_text"><p>НЕДАВНО ВЫ СМОТРЕЛИ:</p></div>
    <hr noshade size="1">
    <div id="viewed_list">
        <div class="prev_viewed">
            <img src="/img/catalog_prev.png">
        </div>
        <div class="block_available">
            <div class="catalog_available">
                <img src="/img/catalog_photo1.jpg">
            </div>
            <p>SG905700N</p>
        </div>
        <div class="block_available">
            <div class="catalog_available">
                <img src="/img/catalog_photo1.jpg">
            </div>
            <p>SG905700N</p>
        </div>
        <div class="block_available">
            <div class="catalog_available">
                <img src="/img/catalog_photo1.jpg">
            </div>
            <p>SG905700N</p>
        </div>
        <div class="block_available" style="margin-right: 0 !important">
            <div class="catalog_available">
                <img src="/img/catalog_photo1.jpg">
            </div>
            <p>SG905700N</p>
        </div>
        <div class="next_viewed">
            <img src="/img/catalog_next.png">
        </div>
    </div><!--viewed_list-->
</div> <!--viewed-->