<div id="left_catalog">
    <p class="back_to_resault">&lt;&lt; <a href="#" onclick="history.back(); return false;">назад&nbsp;&nbsp;к&nbsp;&nbsp;результатам</a></p>
    <hr noshade size="1">
    <p class="left_catalog_point">КОЛЛЕКЦИИ</p>
    <?php foreach ($this->brands as $brand): ?>
        <div class="area">
            <p><a href="<?php echo $brand['url'] ?>" class="area-link"><?php echo $brand['title'] ?></a></p>
        </div>
    <?php endforeach; ?>
<!--    <div id="dekor">-->
<!--        <hr noshade size="1">-->
<!--        <p class="left_catalog_point">ДЕКОР</p>-->
<!--        <img src="/img/dekor_1.jpg">-->
<!--        <p class="dekor_model">B1726/SG9057</p>-->
<!--        <p class="dekor_size">30*7,2*8</p>-->
<!--        <img src="/img/dekor_2.jpg">-->
<!--        <p class="dekor_model">B1726/SG9057</p>-->
<!--        <p class="dekor_size">30*7,2*8</p>-->
<!--        <img src="/img/dekor_3.jpg">-->
<!--        <p class="dekor_model">B1726/SG9057</p>-->
<!--        <p class="dekor_size">30*7,2*8</p>-->
<!--        <img src="/img/dekor_4.jpg">-->
<!--        <p class="dekor_model">C1964/SG8014</p>-->
<!--        <p class="dekor_size">96*96*11</p>-->
<!--    </div>-->
</div><!--left_catalog-->
<div id="right_catalog">
    <div class="nav_catalog">
        <p><a href="/">Главная</a>
            <span>/</span>
            <a href="/<?php echo $this->product['category_page_url'] ?>"><?php echo $this->product['category_title'] ?></a>
            <span>/</span>
            <a href="/<?php echo $this->product['category_page_url'] ?>/<?php echo $this->product['brand_page_url'] ?>">
                <?php echo $this->product['brand_title'] ?>
            </a>
            <span>/</span>
            <?php echo $this->product['title'] ?></p>
    </div>
    <div>
        <p class="name_black" style="text-transform: uppercase"><?php echo $this->product['title'] ?></p>
        <p class="name_blue" style="text-transform: uppercase"><?php echo $this->product['brand_title'] ?></p>
        <div class="catalog_sample">
            <img style="width:280px;" class="product-image" src="/files/thumbnail/<?php echo $this->product['image'] ?>"/>
        </div>
        <div class="sample_price">
            <p class="price_catalog"> <span class="product-cost"><?php echo $this->product['cost'] ?></span> <span class="product-cost-measure">руб./м</span></p>
            <p><span class="param-label">Тип поверхности:</span> <span class="product-surface"><?php echo $this->product['surface_title'] ?></span></p>
            <p><span class="param-label">Размер:</span> <?php echo $this->product['width'] ?>*<?php echo $this->product['height'] ?>*<?php echo $this->product['depth'] ?></p>
<!--            <p><span>Рисунок:</span> дерево</p>-->
<!--            <p><span>Цвет:</span> серый</p>-->
            <input type="button" id="catalog_button" value="" onclick="location.href = '<?php echo $this->url(array(), 'feedback') ?>'">
        </div>
    </div>
    <div id="catalog_info">
        <?php echo $this->product['content'] ?>
    </div>
    <div id="available">
        <p class="left_catalog_point">ДОСТУПНЫЕ ЦВЕТА:</p>
        <?php foreach ($this->productColors as $color): ?>
            <div class="block_available">
                <div class="catalog_available">
                    <a href="#" class="product-color" data-pc-image="<?php echo $color['image'] ?>" data-pc-cost="<?php echo $color['cost'] ?>" data-pc-surface="<?php echo $color['color_surface'] ?>">
                        <img src="/files/thumbnail/<?php echo $color['image'] ?>">
                    </a>
                </div>
                <p>
                    <a href="#" class="product-color" data-pc-image="<?php echo $color['image'] ?>" data-pc-cost="<?php echo $color['cost'] ?>" data-pc-surface="<?php echo $color['color_surface'] ?>">
                        <?php echo $color['title'] ?>
                    </a>
                </p>
            </div>
        <?php endforeach; ?>
    </div>
    <script>
        $('.product-color').on('click', function(){
            var cost = $(this).attr('data-pc-cost');
            var image = $(this).attr('data-pc-image');
            var surface = $(this).attr('data-pc-surface');
            $('.product-cost').html(cost);
            $('.product-surface').html(surface);
            $('.product-image').attr('src', '/files/thumbnail/' + image);
            return false;
        });
    </script>
</div>
<?php if (!empty($this->lastViewed)): ?>
<div id="viewed">
    <div id="viewed_text"><p>НЕДАВНО ВЫ СМОТРЕЛИ:</p></div>
    <hr noshade size="1">
    <div id="viewed_list">
        <div class="prev_viewed">
            <img src="/img/catalog_prev.png">
        </div>
        <?php foreach ($this->lastViewed as $lastViewed): ?>
            <?php echo $this->partial('secondaryItem.phtml', array('item' => $lastViewed)); ?>
        <?php endforeach; ?>
        <div class="next_viewed">
            <img src="/img/catalog_next.png">
        </div>
    </div><!--viewed_list-->
</div> <!--viewed-->
<?php endif; ?>
<?php if (!empty($this->recommended)): ?>
<div id="viewed">
    <div id="viewed_text"><p>АКЦИЯ:</p></div>
    <hr noshade size="1">
    <div id="viewed_list">
        <div class="prev_viewed">
            <img src="/img/catalog_prev.png">
        </div>
        <?php foreach ($this->recommended as $recommendedItem): ?>
            <?php echo $this->partial('secondaryItem.phtml', array('item' => $recommendedItem)); ?>
        <?php endforeach; ?>
        <div class="next_viewed">
            <img src="/img/catalog_next.png">
        </div>
    </div><!--viewed_list-->
</div> <!--viewed-->
<?php endif; ?>