<div id="left_catalog">
    <p class="back_to_resault">&lt;&lt; <a href="#" onclick="history.back(); return false;">назад&nbsp;&nbsp;к&nbsp;&nbsp;результатам</a></p>
    <hr noshade size="1">
    <?php if (!empty($this->collections)): ?>
        <p class="left_catalog_point">КОЛЛЕКЦИИ</p>
        <?php foreach ($this->collections as $collection): ?>
            <div class="area">
                <p><a href="<?php echo $collection['url'] ?>" class="area-link"><?php echo $collection['title'] ?></a></p>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div><!--left_catalog-->
<div id="right_catalog">
    <div class="nav_catalog">
        <p>
            <noindex><a href="/" rel='nofollow'>Главная</a></noindex>
            <span>/</span>
            <a href="/<?php echo $this->product['category_page_url'] ?>"><?php echo $this->product['category_title'] ?></a>
            <span>/</span>
            <a href="/<?php echo $this->product['category_page_url'] ?>/<?php echo $this->product['brand_page_url'] ?>">
                <?php echo $this->product['brand_title'] ?>
            </a>
            <span>/</span>
            <?php echo $this->product['title'] ?></p>
    </div>
    <div>
         <p class="name_blue" style="text-transform: uppercase"><?php echo $this->product['brand_title'] ?></p>
         <p class="name_black" style="text-transform: uppercase"><?php echo $this->product['title'] ?></p>
          <div id="catalog_info">
        <?php echo $this->product['content'] ?>
    </div>
        <div class="catalog_sample" id="product-image">
            <a href="/files/<?php echo $this->product['image'] ?>" rel="shadowbox">
                <img style="width:380px;" class="product-image" src="/files/<?php echo $this->product['image'] ?>"/>
            </a>
        </div>
        <div class="sample_price">
            
            <p><span class="param-label">Тип поверхности:</span> <span class="product-surface"><?php echo $this->product['surface_title'] ?></span></p>
            <?php
            $dimensions = '';
            if ($this->product['width'] && $this->product['height']) {
                $dimensions .= "{$this->product['width']}*{$this->product['height']}";
            }
            if ($this->product['depth']) {
                $dimensions .= empty($dimensions) ? '' : '*';
                $dimensions .= $this->product['depth'];
            }
            ?>
            <?php if (!empty($dimensions)): ?>
            <p><span class="param-label">Размер:</span> <?php echo $dimensions; ?></p>
            <?php endif; ?>
            <input type="button" id="catalog_button" value="" onclick="location.href = '<?php echo $this->url(array(), 'feedback') ?>'">
          <p class="price_catalog"> <span class="product-cost"><?php echo (int) $this->product['cost'] ?></span> <span class="product-cost-measure">руб./м</span></p>
        </div>
    </div>
    <?php if (!empty($this->productColors)): ?>
    <div id="available">
        <p class="left_catalog_point">ДОСТУПНЫЕ ЦВЕТА:</p>
        <?php foreach ($this->productColors as $color): ?>
            <div class="block_available">
                <div class="catalog_available">
                    <a href="#" id="color-<?php echo $color['id'] ?>" class="product-color" data-pc-image="<?php echo $color['image'] ?>" data-pc-cost="<?php echo (int) $color['cost'] ?>" data-pc-surface="<?php echo $color['color_surface'] ?>">
                        <img src="/files/<?php echo $color['image_preview'] ?>">
                    </a>
                </div>
                <p>
                    <a href="#" class="product-color" data-pc-image="<?php echo $color['image'] ?>" data-pc-cost="<?php echo (int) $color['cost'] ?>" data-pc-surface="<?php echo $color['color_surface'] ?>">
                        <?php echo $color['title'] ?>
                    </a>
                </p>
            </div>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>

    <script>

        var setProductColor = function($elm){
            var cost = $elm.attr('data-pc-cost');
            var image = $elm.attr('data-pc-image');
            var surface = $elm.attr('data-pc-surface');
            $('.product-cost').html(cost);
            $('.product-surface').html(surface);
            $('.product-image').attr('src', '/files/' + image);

        }

        $('#available .product-color').on('click', function(){
            setProductColor($(this));
            $('html, body').animate({
                scrollTop: $("#right_catalog").offset().top
            }, 400);

            return false;
        });
        var hash = window.location.hash;
        console.log(hash);
        if (hash.slice(0, 8) == '#!color-') {
            setProductColor($('#' + hash.slice(2)));
        }
    </script>
   
    <?php if (!empty($this->productDecors)): ?>
    <div class="groupfix pr-gallery">
        <p class="left_catalog_point">Декоры:</p>
        <?php foreach ($this->productDecors as $color): ?>
            <div class="block_available">
                <div class="catalog_available">
                    <a href="/files/<?php echo $color['image'] ?>" class="product-color" title="<?php echo $color['title'] ?>"  rel="shadowbox">
                        <img src="/files/<?php echo $color['image_preview'] ?>">
                    </a>
                </div>
                <p><?php echo $color['title'] ?></p>
            </div>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
     <?php if (!empty($this->productInters)): ?>
    <div class="groupfix pr-gallery">
        <p class="left_catalog_point">Интерьеры:</p>
        <?php foreach ($this->productInters as $color): ?>
            <div class="block_available">
                <div class="catalog_available">
                    <a href="/files/<?php echo $color['image'] ?>" class="product-color" title="<?php echo $color['title'] ?>"  rel="shadowbox">
                        <img src="/files/<?php echo $color['image_preview'] ?>">
                    </a>
                </div>
                <p><?php echo $color['title'] ?></p>
            </div>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
</div>
<?php if (!empty($this->lastViewed)): ?>
<div id="viewed">
    <div id="viewed_text"><p>НЕДАВНО ВЫ СМОТРЕЛИ:</p></div>
    <hr noshade size="1">
    <div id="viewed_list">
        <div class="prev_viewed">
            <img src="/img/catalog_prev.png">
        </div>
        <?php foreach ($this->lastViewed as $lastViewed): ?>
            <?php echo $this->partial('secondaryItem.phtml', array('item' => $lastViewed)); ?>
        <?php endforeach; ?>
        <div class="next_viewed">
            <img src="/img/catalog_next.png">
        </div>
    </div><!--viewed_list-->
</div> <!--viewed-->
<?php endif; ?>
<?php if (!empty($this->recommended)): ?>
<div id="viewed">
    <div id="viewed_text"><p>АКЦИЯ:</p></div>
    <hr noshade size="1">
    <div id="viewed_list">
        <div class="prev_viewed">
            <img src="/img/catalog_prev.png">
        </div>
        <?php foreach ($this->recommended as $recommendedItem): ?>
            <?php echo $this->partial('secondaryItem.phtml', array('item' => $recommendedItem)); ?>
        <?php endforeach; ?>
        <div class="next_viewed">
            <img src="/img/catalog_next.png">
        </div>
    </div><!--viewed_list-->
</div> <!--viewed-->
<?php endif; ?>