<h2><?php echo $this->item['title']; ?>

    <?php
    $label = 'другое';
    switch ($this->item['entity']) {
        case 'page':
            $value = 'страница';
            $type = 'default';
            break;
        case 'brand':
            $value = 'бренд';
            $type = 'success';
            break;
        case 'category':
            $value = 'категория';
            $type = 'success';
            break;
        case 'news':
            $value = 'новость';
            $type = 'info';
            break;
        case 'product':
            $value = 'продукт';
            $type = 'success';
            break;
        case 'rek':
            $value = 'рекомендация';
            $type = 'warning';
            break;
        default:
            $value = 'другое';
            $type = 'important';
    }
    echo '<small>' . $value . '</small>';
    ?>
</h2>

<p>
    <a title="Редактировать"
       href="<?php echo $this->url(array('action' => 'edit', 'controller' => $this->item['entity'], 'id' => $this->item['id'], 'module' => 'admin'), 'default') ?>"
       role="button" class="btn btn-primary add"><i class="icon-edit icon-white"></i> Редактировать</a>
<?php if (subentity($this->item['entity'])): ?>
    <a title="Добавить страницу"
        href="<?php echo $this->url(array('action' => 'add', 'controller' => subentity($this->item['entity']), 'idParent' => $this->item['id'], 'module' => 'admin'), 'default') ?>"
        role="button" class="btn btn-success add"><i class="icon-plus icon-white"></i> Добавить страницу</a>

<?php endif; ?>
</p>

<?php if (count($this->subItems) > 0): ?>
<table class="table table-hover table-striped">
    <thead>
    <tr>
        <th></th>
        <th>№</th>
        <th>Заголовок</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->subItems as $item): ?>
        <tr>
            <td style="width: 20px;"><?php if ($item['is_published']): ?><i class="icon-ok"></i><?php endif; ?></td>
            <td style="width:30px;"><?php echo $item['order'] ?></td>
            <td><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => $item['entity'], 'action' => 'edit'), 'admin') ?>"><?php echo $item['title'] ?></a></td>
            <td style="width: 80px; text-align: right;">
                <?php
                    $label = 'другое';
                    switch ($item['entity']) {
                        case 'page':
                            $value = 'страница';
                            $type = 'default';
                            break;
                        case 'brand':
                            $value = 'бренд';
                            $type = 'success';
                            break;
                        case 'category':
                            $value = 'категория';
                            $type = 'success';
                            break;
                        case 'news':
                            $value = 'новость';
                            $type = 'info';
                            break;
                        case 'product':
                            $value = 'продукт';
                            $type = 'success';
                            break;
                        case 'rek':
                            $value = 'рекомендация';
                            $type = 'warning';
                            break;
                        default:
                            $value = 'другое';
                            $type = 'important';
                    }
                echo '<span class="badge badge-' . $type . '">' . $value . '</span>';
                ?>
            </td>
            <td style="width: 40px;"><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => $item['entity'], 'action' => 'delete'), 'admin') ?>" class="icon-trash pull-right action delete"></a></td>
            <td style="width: 40px;"><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => $item['entity'], 'action' => 'edit'), 'admin') ?>" class="icon-edit pull-right action edit"></a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>