<h2><?php echo $this->item['title']; ?></h2>

<?php if (subentity($this->item['entity'])): ?>
    <p><a title="Добавить подпункт"
       href="<?php echo $this->url(array('action' => 'add', 'controller' => subentity($this->item['entity']), 'idParent' => $this->item['id'], 'module' => 'admin'), 'default') ?>"
       role="button" class="btn btn-success add">Добавить подпункт</a></p>
<?php endif; ?>

<?php if (!empty($this->subItems)): ?>

<h2>Подпункты:</h2>
<table class="table table-hover table-striped">
    <thead>
    <tr>
        <th>Опубликован</th>
        <th>Заголовок</th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->subItems as $item): ?>
        <tr>
            <td style="width: 100px;"><?php if ($item['is_published']): ?><i class="icon-ok"></i><?php endif; ?></td>
            <td><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => $item['entity'], 'action' => 'edit'), 'admin') ?>"><?php echo $item['title'] ?></a></td>
            <td style="width: 40px;"><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => $item['entity'], 'action' => 'delete'), 'admin') ?>" class="icon-trash pull-right action delete"></a></td>
            <td style="width: 40px;"><a href="<?php echo $this->url(array('id' => $item['id'], 'controller' => $item['entity'], 'action' => 'edit'), 'admin') ?>" class="icon-edit pull-right action edit"></a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>